# ~/.config/starship.toml

add_newline = true

format = '''
[┌─>](bold #a6e3a1) $aws$gcloud$azure
[│](bold #a6e3a1)   $time$kubernetes $git_branch$git_status $python $nodejs $golang $helm
[└─>](bold #a6e3a1) $cmd_duration$directory $character'''

# Changes the default prompt symbol to '>'
[character]
success_symbol = "[❯](bold #a6e3a1)"
error_symbol = "[❯](bold #f38ba8)"

# --- Cloud & Containerization Modules ---

# AWS module - shows current profile and region
[aws]
symbol = "AWS ☁️  "
style = "bold #f9e2af"
format = "[$symbol($profile \\($region\\))]($style) "
force_display = true

# GCP module - shows current project and region
[gcloud]
symbol = "GCP ☁️  "
style = "bold #89b4fa"
format = "[$symbol($project \\($region\\))]($style) "
disabled = false

[line_break]
disabled = false

[azure]
disabled = false
format = "[$symbol($username)]($style) "
symbol = "AZ ☁️  "
style = "bold #cba6f7"

# Kubernetes module - shows context and namespace
[kubernetes]
symbol = "⚓"
style = "bold #94e2d5"
format = '[$symbol$context \[$namespace\]]($style) '
disabled = false

# Shorten long EKS context names
[[kubernetes.contexts]]
context_pattern = "arn:aws:eks:us-east-1:418274023911:cluster/internal"
context_alias = "internal"

# Helm module - shows active chart version
[helm]
symbol = "⎈ "
format = "via [$symbol($version)]($style) "
disabled = false

# --- Programming Language & Environment Modules ---

# Go module - shows Go version
[golang]
symbol = "🐹 "
style = "bold #89b4fa"
format = "via [$symbol($version)]($style) "

# Node.js module - shows Node.js version
[nodejs]
symbol = "⬢ "
style = "bold #a6e3a1"
format = "via [$symbol($version)]($style) "
disabled = false

# Python module - shows version and virtual environment
[python]
symbol = "🐍 "
style = "bold #f9e2af"
pyenv_version_name = false
format = 'via [$symbol${pyenv_prefix}(${version} )(\\($virtualenv\\))]($style)'

# --- Core & High-Utility Modules ---

# Git module - shows branch and status
[git_branch]
symbol = "🌿 "
style = "bold #a6e3a1"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #f38ba8"
format = '([$all_status$ahead_behind]($style)) '
stashed = "📦"
ahead = "↑"
behind = "↓"
diverged = "⇕"
renamed = "»"
deleted = "✘"

# Directory module - shows current path
[directory]
style = "bold #94e2d5"
read_only = "🔒"
truncate_to_repo = true
truncation_length = 3

# Cmd_duration module - shows last command execution time
[cmd_duration]
min_time = 500
style = "bold #f9e2af"
format = "took [$duration]($style) "

# Time module - shows current time
[time]
disabled = false
style = "dimmed #bac2de"
format = "[$time]($style) "
time_format = "%T"
