gui:
  showFileIcons: false
  theme:
    activeBorderColor: ["#88c0d0", bold]
    inactiveBorderColor: ["#4c566a"]
    optionsTextColor: ["#81a1c1"]
    selectedLineBgColor: ["#434c5e"]
    cherryPickedCommitBgColor: ["#434c5e"]
    cherryPickedCommitFgColor: ["#b48ead"]
    unstagedChangesColor: ["#bf616a"]
    defaultFgColor: ["#d8dee9"]
update:
  method: never
