gui:
  theme:
    activeBorderColor: ["#88c0d0", bold]
    inactiveBorderColor: ["#4c566a"]
    selectedLineBgColor: ["#434c5e"]
    optionsTextColor: ["#81a1c1"]
logs:
  timestamps: true
  since: 1h
  tail: "300"
commandTemplates:
  dockerCompose: docker compose
